apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: back-office

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql.yaml
  - redis.yaml
  - zookeeper.yaml
  - kafka.yaml
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
  - back-office-app.yaml

